Added thread_requests parameter to import_pbp_data and import_weekly …
cooperdff/nfl_data_py pull request #46
Opened 2023-04-21 12:51 UTC by bendominguez0111

…data functions.

Added optional parameter to import_pbp_data and import_weekly_data to use threading to speed up requests for play by play data and weekly data. I also tested async and multiprocessing as well but threading posted the best results. Depending on connection, it sped up the speed at which PBP data from 1999 to 2022 was loaded by 25-50%. 

Also added associated tests. I added a __init__.py file to the tests folder, because it was the only way I could run pytest (although I may have done something wrong there).

Did not open issue for this beforehand but spoke to @cooperdff on Twitter about the idea and thought it was a good idea. 

Test results below:

![image](https://user-images.githubusercontent.com/59814501/233640445-099d31c9-7c2d-444e-aa75-127c29bb09e6.png)

2023-07-14 20:38 UTC, alecglen requested changes
Great idea, @bendominguez0111! Just a couple small fixes needed, plus a question on the dependency addition.

2023-07-14 20:38 UTC, alecglen commented on nfl_data_py/__init__.py
> +    if thread_requests:
Skipped over a little logic change here. As is, it always make the original sequential requests, then optionally requests them _again_ if `thread_requests=True`.

It should be something like 
```
columns = columns or None
if thread_requests:
    with ThreadPoolExecutor() as executor:
        futures = [executor.submit(_read_parquet, url.format(year), year, columns) for year in years]
        data = [future.result() for future in as_completed(futures)]
        data = sorted(data, key=lambda x: x['year'])
        data = [x['data'] for x in data]
else:
    data = [pandas.read_parquet(url.format(x), columns=columns) for x in years]
```

(bonus refactoring to get rid of the columns post-filtering just below this)

2023-07-14 20:38 UTC, alecglen commented on nfl_data_py/tests/nfl_test.py
Out of scope for this PR, but it reminded me that we should have a test for the caching behavior.
```suggestion
		
    # TODO: Add test(s) for cache=True
    
```

2023-07-14 20:38 UTC, alecglen commented on nfl_data_py/tests/nfl_test.py
If you're feeling ambitious, you could assert that this method completes at least as fast as the non-threaded case 😄

2023-07-15 01:09 UTC, bendominguez0111 commented
Cool! I will make some of these changes. I actually thought up another optimization for this but never got to it (removes the need to sort the CSVs at the end, which takes a considerable amount of time if youre pulling a lot of data) I'll add that in as well along with the changes requested

2023-07-21 17:03 UTC, alecglen commented on nfl_data_py/__init__.py
> +    pa = pandas.read_parquet(path, columns=columns, engine='pyarrow')
Adding to this - I ran some performance benchmarks for the two submodules out of curiosity. They were practically identical:
![image](https://github.com/cooperdff/nfl_data_py/assets/28493454/30bcabb4-5838-4bb7-bc03-1f4a77c0598b)

2023-08-05 15:25 UTC, bendominguez0111 commented
Made those changes. Didn't move the `if thread_requests` block all the way down to the `# load data` comment cause it didnt exactly work, but it doesnt bypass caching now w/ this new code. Also set engine = auto instead of explicitly setting pyarrow

2023-08-05 15:27 UTC, bendominguez0111 commented
Oh, and added some additional logic compared to last time to avoid sorting years at the end. Since the HTTP requests can resolve out of order, originally there would need to be a sort at the end which took up some time. Now just creating a fixed sized list and then inserting responses into it as their threads resolve

2023-08-11 22:12 UTC, alecglen approved these changes
Great idea on avoiding the extra sort operation, Ben! All seems to work as intended, just had a couple more quick suggestions you can commit if you like. We'll get this merged soon.

2023-08-20 15:53 UTC, bendominguez0111 commented
Committed those suggestions. Good call, those lines were a bit cluttered

2023-09-02 03:50 UTC, merged